version: '3.5'

services:
  postgresdb:
    image: postgres:latest
    container_name: costdb
    restart: always
    ports:
      - "6543:5432"
    environment:
      POSTGRES_USER: efim
      POSTGRES_PASSWORD: 25121997
      DB_NAME: postgres
    networks:
      - cost

  costcalculator:
    image: costcalculatorimage
    container_name: costcalculator
    build: .
    restart: always
    ports:
      - "8085:8085"
    depends_on:
      - postgresdb
    networks:
      - cost

networks:
  cost:
    name: costbackend