version: '3.5'

services:
  postgresdb:
    image: postgres:latest
    container_name: costDB
    restart: always
    ports:
      - "6543:5432"
    environment:
      POSTGRES_USER: testUser
      POSTGRES_PASSWORD: testPassword
      DB_NAME: postgres
    networks:
      - cost

  redis:
    image: redis:latest
    container_name: example-redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./settings/redis/.ash_history:/root/.ash_history
      - ./settings/redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - cost

  costcalculator:
    image: costcalculatorimage
    container_name: costcalculator
    build: .
    env_file: .env
    restart: always
    ports:
      - "8085:8085"
    depends_on:
      - postgresdb
      - redis
    networks:
      - cost

networks:
  cost:
    name: costbackend